databases:
  - name: amigos-db

services:
  - type: web
    name: amigos-flashcards
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amigos-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20"

